Controllers/Pet_OwnerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Future_Vet.Models;

namespace Future_Vet.Controllers
{
    public class Pet_OwnerController : Controller
    {
        private Future_VetEntities db = new Future_VetEntities();

        // GET: Pet_Owner
        public ActionResult Index()
        {

            if (Session["IDUser"] != null)//check if user is logged in
            {
                return View(db.Pet_Owner.ToList());
            }
            else
            {
                return RedirectToAction("Login");
            }
          
        }

        // GET: Pet_Owner/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Owner pet_Owner = db.Pet_Owner.Find(id);
            if (pet_Owner == null)
            {
                return HttpNotFound();
            }
            return View(pet_Owner);
        }

        // GET: Pet_Owner/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pet_Owner/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Create([Bind(Include = "IDOwner,Name,Surname,Phone,Email,Postal,Id_Number,Account")] Pet_Owner pet_Owner)
        {
            if (ModelState.IsValid)
            {
                db.Pet_Owner.Add(pet_Owner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pet_Owner);
        }

        // GET: Pet_Owner/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Owner pet_Owner = db.Pet_Owner.Find(id);
            if (pet_Owner == null)
            {
                return HttpNotFound();
            }
            return View(pet_Owner);
        }

        // POST: Pet_Owner/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Edit([Bind(Include = "IDOwner,Name,Surname,Phone,Email,Postal,Id_Number,Account")] Pet_Owner pet_Owner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pet_Owner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pet_Owner);
        }

        // GET: Pet_Owner/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Owner pet_Owner = db.Pet_Owner.Find(id);
            if (pet_Owner == null)
            {
                return HttpNotFound();
            }
            return View(pet_Owner);
        }

        // POST: Pet_Owner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult DeleteConfirmed(decimal id)
        {
            Pet_Owner pet_Owner = db.Pet_Owner.Find(id);
            db.Pet_Owner.Remove(pet_Owner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/Pet_VisitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Future_Vet.Models;
using Microsoft.AspNetCore.Mvc;

namespace Future_Vet.Controllers
{
    public class Pet_VisitController : Controller
    {
        private Future_VetEntities db = new Future_VetEntities();

        // GET: Pet_Visit
        public ActionResult Index()
        {

            if (Session["IDUser"] != null)//check if user is logged in
            {
                var pet_Visit = db.Pet_Visit.Include(p => p.Pet_Details).Include(p => p.Vet);

                return View(pet_Visit.ToList());
            }
            else
            {
                return RedirectToAction("Login");
            }

          
        }
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Visit pet_Visit = db.Pet_Visit.Find(id);
            if (pet_Visit == null)
            {
                return HttpNotFound();
            }
            return View(pet_Visit);
        }
        public ActionResult Create()
        {
            ViewBag.IDPet = new SelectList(db.Pet_Details, "IDPet", "Pet_Name");
            ViewBag.IDVet = new SelectList(db.Vets, "IDVet", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Create(FormCollection collection)
        {
            Pet_Visit PetVisit = new Pet_Visit();

            if (ModelState.IsValid)
            {

                PetVisit.VisitDate = Convert.ToDateTime(collection["datepicker1"]);
                PetVisit.VisitTime = TimeSpan.Parse(collection["tmFrom"]);
                PetVisit.IDPet = Convert.ToDecimal(collection["IDPet"]);
                PetVisit.IDVet = Convert.ToDecimal(collection["IDVet"]);
                PetVisit.Summary = collection["txtComment"];


                db.Pet_Visit.Add(PetVisit);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            ViewBag.IDPet = new SelectList(db.Pet_Details, "IDPet", "Pet_Name", PetVisit.IDPet);
            ViewBag.IDVet = new SelectList(db.Vets, "IDVet", "Name", PetVisit.IDVet);
            return View(PetVisit);
        }
       
        // GET: Pet_Visit/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Visit pet_Visit = db.Pet_Visit.Find(id);
            if (pet_Visit == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDPet = new SelectList(db.Pet_Details, "IDPet", "Pet_Name", pet_Visit.IDPet);
            ViewBag.IDVet = new SelectList(db.Vets, "IDVet", "Name", pet_Visit.IDVet);
            return View(pet_Visit);
        }

        // POST: Pet_Visit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Edit([Bind(Include = "IDVisit,VisitDate,VisitTime,IDPet,IDVet,Summary")] Pet_Visit pet_Visit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pet_Visit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDPet = new SelectList(db.Pet_Details, "IDPet", "Pet_Name", pet_Visit.IDPet);
            ViewBag.IDVet = new SelectList(db.Vets, "IDVet", "Name", pet_Visit.IDVet);
            return View(pet_Visit);
        }

        // GET: Pet_Visit/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Visit pet_Visit = db.Pet_Visit.Find(id);
            if (pet_Visit == null)
            {
                return HttpNotFound();
            }
            return View(pet_Visit);
        }

        // POST: Pet_Visit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult DeleteConfirmed(decimal id)
        {
            Pet_Visit pet_Visit = db.Pet_Visit.Find(id);
            db.Pet_Visit.Remove(pet_Visit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Future_Vet.Models;

namespace Future_Vet.Controllers
{
    public class UsersController : Controller
    {
        private Future_VetEntities db = new Future_VetEntities();

        // GET: Users
        public ActionResult Index()
        {
            if (Session["IDUser"] != null)//check if user is logged in
            {
                return View(db.Users.ToList());
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        // GET: Users/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDUser,Name,Surname,Email,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDUser,Name,Surname,Email,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/VetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Future_Vet.Models;

namespace Future_Vet.Controllers
{
    public class VetsController : Controller
    {
        private Future_VetEntities db = new Future_VetEntities();

        // GET: Vets
        public ActionResult Index()
        {

            if (Session["IDUser"] != null)//check if user is logged in
            {
                return View(db.Vets.ToList());
            }
            else
            {
                return RedirectToAction("Login");
            } 
        }

        // GET: Vets/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vet vet = db.Vets.Find(id);
            if (vet == null)
            {
                return HttpNotFound();
            }
            return View(vet);
        }

        // GET: Vets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Create(FormCollection collection)
        {

         Vet VetDetaill= new Vet();
            string Address = collection["txtAddress"];
          

            if (ModelState.IsValid)
            {
                VetDetaill.Name = collection["Name"];
                VetDetaill.Surname = collection["Surname"];
                VetDetaill.Id_Number =collection["Id_Number"];
                VetDetaill.License = collection["License"];
                VetDetaill.Address= Address;


                db.Vets.Add(VetDetaill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View();
        }

        // GET: Vets/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vet vet = db.Vets.Find(id);
            if (vet == null)
            {
                return HttpNotFound();
            }
            return View(vet);
        }

        // POST: Vets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Edit([Bind(Include = "IDVet,Name,Surname,Id_Number,License,Address")] Vet vet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vet);
        }

        // GET: Vets/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vet vet = db.Vets.Find(id);
            if (vet == null)
            {
                return HttpNotFound();
            }
            return View(vet);
        }

        // POST: Vets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult DeleteConfirmed(decimal id)
        {
            Vet vet = db.Vets.Find(id);
            db.Vets.Remove(vet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Site.css" rel="stylesheet">
    <script>
        function htmlbodyHeightUpdate() {
            var height3 = $(window).height()
            var height1 = $('.nav').height() + 50
            height2 = $('.main').height()
            if (height2 > height3) {
                $('html').height(Math.max(height1, height3, height2) + 10);
                $('body').height(Math.max(height1, height3, height2) + 10);
            }
            else {
                $('html').height(Math.max(height1, height3, height2));
                $('body').height(Math.max(height1, height3, height2));
            }

        }
        $(document).ready(function () {
            htmlbodyHeightUpdate()
            $(window).resize(function () {
                htmlbodyHeightUpdate()
            });
            $(window).scroll(function () {
                height2 = $('.main').height()
                htmlbodyHeightUpdate()
            });
        })


    </script>
</head>
<body>
    <nav class="navbar navbar-inverse sidebar" style="padding-left: 1%" role="navigation" id="SiteMenu" runat="server">
        <div class="container-fluid">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Appointments<span class="caret"></span><span style="font-size: 14px" class="pull-right hidden-xs showopacity glyphicon glyphicon-wrench"></span></a>
                        <ul class="dropdown-menu forAnimate " role="menu">
                            <li><a onclick='window.location = "@Url.Action("Create", "Pet_Visit")";'>New Appointment</a></li>
                            <li><a onclick='window.location = "@Url.Action("Index", "Pet_Visit")";'>View Appointments</a></li>

                        </ul>
                    </li>
                    @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Finance<span class="caret"></span><span style="font-size: 14px" class="pull-right hidden-xs showopacity glyphicon glyphicon-folder-open"></span></a>
                        <ul class="dropdown-menu forAnimate " role="menu">
                            <li><a href="#">Ageing</a></li>
                            <li><a onclick='window.location = "@Url.Action("Index", "Invoices")";'>Invoice</a></li>
                            <li><a onclick='window.location = "@Url.Action("Index", "Receipts")";'>Payments</a></li>

                        </ul>
                    </li>*@
                    <li class="dropdown" id="mAdmin" runat="server" visible="False">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<span class="caret"></span><span style="font-size: 14px" class="pull-right hidden-xs showopacity glyphicon glyphicon-pencil"></span></a>
                        <ul class="dropdown-menu forAnimate" role="menu">
                            <li><a onclick='window.location = "@Url.Action("Index", "Users")";'>Employees</a></li>
                            <li><a onclick='window.location = "@Url.Action("Index", "Pet_Details")";'>Pet Details</a></li>
                            <li><a onclick='window.location = "@Url.Action("Index", "Pet_Owner")";'>Pet Owner</a></li>
                            <li><a onclick='window.location = "@Url.Action("Index", "Vets")";'>Vet Details</a></li>
                        </ul>
                    </li>
                    <li><a onclick='window.location = "@Url.Action("Login", "Login")";'>Logout<span style="font-size: 14px" class="pull-right hidden-xs showopacity glyphicon glyphicon-log-out"></span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="col-xs-10 container body-content" style="background-color:#fff;border-radius:5px;height:95vh">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>