Models/Pet_Details.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Future_Vet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet_Details()
        {
            this.Pet_Visit = new HashSet<Pet_Visit>();
        }
    
        public decimal IDPet { get; set; }
        public string Pet_Name { get; set; }
        public Nullable<decimal> IDOwner { get; set; }
        public Nullable<decimal> IDBreed { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<decimal> IDAnimal_Type { get; set; }
        public string TagNumber { get; set; }
    
        public virtual Animal_Breed Animal_Breed { get; set; }
        public virtual Animal_Type Animal_Type { get; set; }
        public virtual Pet_Owner Pet_Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet_Visit> Pet_Visit { get; set; }
    }
}

Controllers/Pet_DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Future_Vet.Models;

namespace Future_Vet.Controllers
{
    public class Pet_DetailsController : Controller
    {
        private Future_VetEntities db = new Future_VetEntities();

        // GET: Pet_Details
        public ActionResult Index()
        {
            if (Session["IDUser"] != null)//check if user is logged in
            {
                var pet_Details = db.Pet_Details.Include(p => p.Animal_Breed).Include(p => p.Animal_Type).Include(p => p.Pet_Owner);
                return View(pet_Details.ToList());
            }
            else
            {
                return RedirectToAction("Login");
            }
           
        }

        // GET: Pet_Details/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Details pet_Details = db.Pet_Details.Find(id);
            if (pet_Details == null)
            {
                return HttpNotFound();
            }
            return View(pet_Details);
        }

        // GET: Pet_Details/Create
        public ActionResult Create()
        {
            ViewBag.IDBreed = new SelectList(db.Animal_Breed, "IDBreed", "Breed");
            ViewBag.IDAnimal_Type = new SelectList(db.Animal_Type, "IDAnimal_Type", "Animal_Type1");
            ViewBag.IDOwner = new SelectList(db.Pet_Owner, "IDOwner", "Name");//need to combine to get fullname of owner
            return View();
        }

        // POST: Pet_Details/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Create(FormCollection collection)
        {


            Pet_Details PetDetaill = new Pet_Details();
            string Birthdate = collection["txtAddress"];


            if (ModelState.IsValid)
            {
                PetDetaill.Pet_Name = collection["Pet_Name"];
                PetDetaill.IDOwner = Convert.ToDecimal(collection["IDOwner"]);
                PetDetaill.IDBreed = Convert.ToDecimal(collection["IDBreed"]);
                PetDetaill.Birthdate = Convert.ToDateTime(Birthdate);
                PetDetaill.IDAnimal_Type = Convert.ToDecimal(collection["IDAnimal_Type"]);
                PetDetaill.TagNumber = collection["TagNumber"];


                db.Pet_Details.Add(PetDetaill);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            

            ViewBag.IDBreed = new SelectList(db.Animal_Breed, "IDBreed", "Breed", PetDetaill.IDBreed);
            ViewBag.IDAnimal_Type = new SelectList(db.Animal_Type, "IDAnimal_Type", "Animal_Type1", PetDetaill.IDAnimal_Type);
            ViewBag.IDOwner = new SelectList(db.Pet_Owner, "IDOwner", "Name", PetDetaill.IDOwner);//need to combine to get fullname of owner
            return View(PetDetaill);
        }

        // GET: Pet_Details/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Details pet_Details = db.Pet_Details.Find(id);
            if (pet_Details == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDBreed = new SelectList(db.Animal_Breed, "IDBreed", "Breed", pet_Details.IDBreed);
            ViewBag.IDAnimal_Type = new SelectList(db.Animal_Type, "IDAnimal_Type", "Animal_Type1", pet_Details.IDAnimal_Type);
            ViewBag.IDOwner = new SelectList(db.Pet_Owner, "IDOwner", "Name", pet_Details.IDOwner);//need to combine to get fullname of owner
            return View(pet_Details);
        }

        // POST: Pet_Details/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult Edit([Bind(Include = "IDPet,Pet_Name,IDOwner,IDBreed,Birthdate,IDAnimal_Type,TagNumber")] Pet_Details pet_Details)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pet_Details).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDBreed = new SelectList(db.Animal_Breed, "IDBreed", "Breed", pet_Details.IDBreed);
            ViewBag.IDAnimal_Type = new SelectList(db.Animal_Type, "IDAnimal_Type", "Animal_Type1", pet_Details.IDAnimal_Type);
            ViewBag.IDOwner = new SelectList(db.Pet_Owner, "IDOwner", "Name", pet_Details.IDOwner);//need to combine to get fullname of owner
            return View(pet_Details);
        }

        // GET: Pet_Details/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet_Details pet_Details = db.Pet_Details.Find(id);
            if (pet_Details == null)
            {
                return HttpNotFound();
            }
            return View(pet_Details);
        }

        // POST: Pet_Details/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Audit]//capture user actions
        public ActionResult DeleteConfirmed(decimal id)
        {
            Pet_Details pet_Details = db.Pet_Details.Find(id);
            db.Pet_Details.Remove(pet_Details);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Pet_Details/Create.cshtml
@model Future_Vet.Models.Pet_Details

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet">

<h3 class="View-title" style="font-size: 3vw">Create a new Pet</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pet_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.EditorFor(model => model.Pet_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pet_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.LabelFor(model => model.IDOwner, "Owner", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    <div style="float:left;" class="form-group col-xs-12">
                        @Html.DropDownList("IDOwner", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDOwner, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDBreed, "Breed", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.DropDownList("IDBreed", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDBreed, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    <div style="float:left;" class="form-group col-xs-12">
                        <input type="text" class="form-control" id="datepicker1" />
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDAnimal_Type, "Animal_Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.DropDownList("IDAnimal_Type", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDAnimal_Type, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.LabelFor(model => model.TagNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.EditorFor(model => model.TagNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TagNumber, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Back" onclick='window.location = "@Url.Action("Index", "Pet_Details")";' class="Green-button" />
                <input type="submit" value="Create" class="Orange-button" />
            </div>
        </div>
    </div>
}
@section Scripts {
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>

    <script type='text/javascript'>
        $('#datepicker1').datepicker({
            dateFormat: "yyyy-MM-dd",
            changeMonth: true,
            changeYear: true,
            showOn: "button",
            buttonText: "<span class='glyphicon glyphicon-calendar'></span>"

        });
    </script>
}

Views/Pet_Details/Delete.cshtml
@model Future_Vet.Models.Pet_Details

@{
    ViewBag.Title = "Delete";
}

<h3 class="View-title"  style="font-size: 3vw">Are you sure you want to delete this?</h3>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pet_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pet_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TagNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TagNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Animal_Breed.Breed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Animal_Breed.Breed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Animal_Type.Animal_Type1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Animal_Type.Animal_Type1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pet_Owner.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pet_Owner.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="button" value="Back" onclick='window.location = "@Url.Action("Index", "Pet_Details")";' class="Green-button" />
    <input type="submit" value="Delete" class="Red-button" />
</div>
    }
</div>

Views/Pet_Details/Details.cshtml
@model Future_Vet.Models.Pet_Details

@{
    ViewBag.Title = "Details";
}

<h3 class="View-title"  style="font-size: 3vw">View selected Pet Details</h3>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pet_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pet_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TagNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TagNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Animal_Breed.Breed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Animal_Breed.Breed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Animal_Type.Animal_Type1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Animal_Type.Animal_Type1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pet_Owner.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pet_Owner.Name)
        </dd>

    </dl>
</div>
<p>
    <input type="button" value="Back" onclick='window.location = "@Url.Action("Index", "Pet_Details")";' class="Green-button" />
    <input type="submit" value="Edit" onclick='window.location = "@Url.Action("Edit", "Pet_Details", new { id = Model.IDPet })";' class="Orange-button" />
</p>

Views/Pet_Details/Edit.cshtml
@model Future_Vet.Models.Pet_Details

@{
    ViewBag.Title = "Edit";
}

<link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet">

<h3 class="View-title" style="font-size: 3vw">Edit Pet Details</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pet_Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDPet)

        <div class="form-group">
            @Html.LabelFor(model => model.Pet_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.EditorFor(model => model.Pet_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pet_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.LabelFor(model => model.IDOwner, "Owner", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.DropDownList("IDOwner", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDOwner, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDBreed, "Breed", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.DropDownList("IDBreed", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDBreed, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    <div style="float:left;" class="form-group col-xs-12">
                        <input type="text" class="form-control" id="datepicker1" />
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDAnimal_Type, "IDAnimal_Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.DropDownList("IDAnimal_Type", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDAnimal_Type, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.LabelFor(model => model.TagNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div style="float:left;" class="form-group col-xs-12">
                    @Html.EditorFor(model => model.TagNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TagNumber, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Back" onclick='window.location = "@Url.Action("Index", "Pet_Details")";' class="Green-button" />
                <input type="submit" value="Save" class="Orange-button" />
            </div>
        </div>
    </div>
}

@section Scripts {
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>

    <cript type='text/javascript'>
        $('#datepicker1').datepicker({
        dateFormat: "yyyy-MM-dd",
        changeMonth: true,
        changeYear: true,
        showOn: "button",
        buttonText: "<span class='glyphicon glyphicon-calendar'></span>"

        });
    </cript>
}

Views/Pet_Details/Index.cshtml
@model IEnumerable<Future_Vet.Models.Pet_Details>

@{
    ViewBag.Title = "Index";
}

<h3 class="View-title"  style="font-size: 3vw">Registered Pets</h3>
<button type="submit" class="Green-button" onclick='window.location = "@Url.Action("Create", "Pet_Details")";'>Add a new Pet</button>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pet_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TagNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Animal_Breed.Breed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Animal_Type.Animal_Type1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pet_Owner.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pet_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TagNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Animal_Breed.Breed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Animal_Type.Animal_Type1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pet_Owner.Name)
            </td>
            <td>
                <input type="submit" value="Edit" onclick='window.location = "@Url.Action("Edit", "Pet_Details", new { id = item.IDPet})";' class="Orange-Small-button" />|
                <input type="submit" value="Details" onclick='window.location = "@Url.Action("Details", "Pet_Details", new { id = item.IDPet})";' class="Blue-Small-button" />|
                <input type="submit" value="Delete" onclick='window.location = "@Url.Action("Delete", "Pet_Details", new { id = item.IDPet})";' class="Red-Small-button" />
            </td>
        </tr>
    }

</table>